spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        enable_lazy_load_no_trans: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost/saving_hour_market?useUnicode=true&characterEncoding=UTF-8
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8082
  error:
    include-stacktrace: ${TRACE_MODE:never}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


google-api-key: ${GOOGLE_API_KEY}
vnpay-hash-secret: ${VNPAY_HASH_SECRET}
vnpay-tmn-code: ${VNPAY_TMN_CODE}

base-path-android: ${BASE_PATH:#{'http://10.0.2.2:8082'}}

