spring:
  devtools:
    restart:
      enabled: off
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        enable_lazy_load_no_trans: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/saving_hour_market?useUnicode=true&characterEncoding=UTF-8
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8082
  error:
    include-stacktrace: ${TRACE_MODE:never}



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


google-api-key: AIzaSyB40Egueby5QI8obTYKCOTcVD-sPzbfWfs
goong-api-key: pjSCY4qPMMbJ4ILtd75FcvXTc3TCO5hataxheWDW
goong-distance-matrix-url: https://rsapi.goong.io/DistanceMatrix
vnpay-hash-secret: ${VNPAY_HASH_SECRET}
vnpay-tmn-code: ${VNPAY_TMN_CODE}

base-path: ${BASE_PATH:#{'http://saving-hour-market.ap-southeast-2.elasticbeanstalk.com'}}
REDIS_HOST: localhost
REDIS_PORT: 6379

