spring:
  jpa:
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        enable_lazy_load_no_trans: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: Dre220413@
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost/saving_hour_market
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8082
